Docker: Add Docker configuration files for multi-environment testing

diff --git a/src/.chezmoiscripts/linux/run_once_before_01_other-wsl-install-packages.sh.tmpl b/src/.chezmoiscripts/linux/run_once_before_01_other-wsl-install-packages.sh.tmpl
--- a/src/.chezmoiscripts/linux/run_once_before_01_other-wsl-install-packages.sh.tmpl
+++ b/src/.chezmoiscripts/linux/run_once_before_01_other-wsl-install-packages.sh.tmpl
@@ -32,11 +32,36 @@ fi
 
 # neovim
 if [ ! -e /usr/bin/nvim ]; then
-  curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
-  chmod u+x nvim.appimage
-  ./nvim.appimage --appimage-extract
-  {{ $sudo }} mv squashfs-root /
-  {{ $sudo }} ln -s /squashfs-root/AppRun /usr/bin/nvim
+  # Detect architecture
+  ARCH=$(uname -m)
+  case $ARCH in
+    x86_64)
+      NEOVIM_ARCH="x86_64"
+      ;;
+    aarch64|arm64)
+      NEOVIM_ARCH="arm64"
+      ;;
+    *)
+      echo "Unsupported architecture: $ARCH"
+      exit 1
+      ;;
+  esac
+  
+  # Download and install Neovim
+  NEOVIM_URL="https://github.com/neovim/neovim/releases/latest/download/nvim-linux-${NEOVIM_ARCH}.tar.gz"
+  
+  echo "Downloading Neovim ${NEOVIM_VERSION} for ${NEOVIM_ARCH}..."
+  curl -LO "$NEOVIM_URL"
+  tar -xzf "nvim-linux-${NEOVIM_ARCH}.tar.gz"
+  
+  # Install to system
+  {{ $sudo }} mv nvim-linux-${NEOVIM_ARCH} /opt/nvim
+  {{ $sudo }} ln -sf /opt/nvim/bin/nvim /usr/bin/nvim
+  
+  # Cleanup
+  rm -f "nvim-linux-${NEOVIM_ARCH}.tar.gz"
+  
+  # Install packer.nvim plugin manager
   git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
 fi
 
